Repository voxpupuli/puppet-lint-param-docs, pull requests merged in 2021-07, with the labels that each got.

#44 Ignore variables in array defaults
  lib/puppet-lint/plugins/check_parameter_documentation.rb
  spec/puppet-lint/plugins/check_parameter_documentation_spec.rb
Labels: bug

#45 Update from voxpupuli modulesync_config
  .github/workflows/release.yml
  .github/workflows/test.yml
  Gemfile
  README.md
  Rakefile
  puppet-lint-param-docs.gemspec
  spec/spec_helper.rb
Labels: modulesync

#46 Release 1.7.5
  CHANGELOG.md
  puppet-lint-param-docs.gemspec
Labels: skip-changelog
