Repository voxpupuli/puppet-lint-param-docs, pull requests merged in 2021-06, with the labels that each got.

#29 Detect faulty documentation style
  README.md
  lib/puppet-lint/plugins/check_parameter_documentation.rb
  spec/puppet-lint/plugins/check_parameter_documentation_spec.rb
Labels: enhancement

#32 release 1.7.0
  .gitignore
  CHANGELOG.md
  puppet-lint-param-docs.gemspec
Labels: skip-changelog

#34 GitHub Actions: Set 0600 perms to gem credentials file
  .github/workflows/release.yml
Labels: bug

#41 fix typo in README.md
  README.md
Labels: skip-changelog

#42 modulesync 2021-06-13
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: modulesync

#43 modulesync 2021-06-15
  .github/workflows/release.yml
  .github/workflows/test.yml
  .gitignore
  Gemfile
Labels: modulesync
